### ISSUE TITLE
Price string is always from price of 1 item, not minimum

### ISSUE THREAD

**Issue by helgatheviking** [helgatheviking/woocommerce-mix-and-match-min-max#1]
@franticpsyx plugin is up and working again, but found this issue with per-item pricing. The min/max (especially the min, which is used for creating price strings) is calculated from the cost of 1 of the cheapest items. It needs to be from the cost of the minimum number of items. MNM already finds the min price, should we just multiply the min price by the min quantity required by this plugin?

**Comment by manospsyx** [comment]
If `get_container_size` by default returns the min item count, then the issue is solved, right?

**Comment by helgatheviking** [comment]
i think it would solve this problem in particular, _but_ then you'd have issues in other places (like validation) where `get_container_size()` needs to return 0 so that we know the item is an "unlimited" product. 

Though it looks like there are opportunities to change the price meta during syncing:
`woocommerce_mnm_update_price_meta` and `woocommerce_mnm_synced`. or we could filter `woocommerce_mnm_get_price` from the mini extension?

**Comment by manospsyx** [comment]
If we only need to use a difference container size just once, for sync, then we can just add a filter here: https://github.com/woothemes/woocommerce-mix-and-match-products/blob/master/includes/class-wc-product-mix-and-match.php#L279

**Comment by helgatheviking** [comment]
Ok, I added some filters here [b15af2](https://github.com/woothemes/woocommerce-mix-and-match-products/commit/b15af2cab6b2bb6b7e6ecbf89d779a1e5cd7c74a) and used them here [716b32](https://github.com/helgatheviking/woocommerce-mix-and-match-min-max/commit/716b32c821ad164ba0ee4bd9de4287cf6416b1fe), but that doesn't seem to solve everything. 
1. There is no sale strikethrough even though one of the items in the container is on sale
2. the sale item is not being selected as the cheapest item (on sale it is the cheapest at $15, the next cheapest regular price is $18, and this one is being selected for the min price... so with a minimum of 2 items the price string is reading "From: $36")

**Comment by manospsyx** [comment]
@helgatheviking 

Just had a look at this. The user must set the container size to unlimited in order to set min/max values? I don't get that.

The easiest way to do it would be to use the original `container_size` meta as the min, and just introduce a new field for the max under the first one, in order to let the existing code do all the work.

I would simply make the container size field show up on an action hook in the back end, and then unhook that and re-hook my own, in order to make it show up as "Min Container Size", using the same input name.

Then, add a second field called "Max Container Size".

Price calculations for the "original" container size are exactly the same as for the min, except we may simply need to add a "From:" string if the max container size > min.

Problem solved. (?)

**Comment by helgatheviking** [comment]
> Just had a look at this. The user must set the container size to unlimited in order to set min/max values? I don't get that.

It wasn't ideal, but it was an easy way to override the fixed quantity checking.

If you replace the `container_size` with a field with the same name, merely labeled "min container size" how do we differentiate between 
1. a container of fixed size, 6
2. a container with a minimum size of 6, and no upper boundary?

since the `container_size` meta would be 6 in both instances?

**Comment by manospsyx** [comment]
> how do we differentiate

In what context?
From a price calc perspective, the min price is still the same, right?
Then we are left with JS:

> Then, add a second field called "Max Container Size".

**Comment by helgatheviking** [comment]
I was thinking in the validation context. If there is a max container size present, you can tell that there is a range. But, what if there is no Max Container size? So min 6, and max is empty/unlimited?

**Comment by manospsyx** [comment]
> a container of fixed size, 6

Min = 6
Max = 6

> a container with a minimum size of 6, and no upper boundary?

Min = 6
Max = 0 or ''

**Comment by helgatheviking** [comment]
That sounds reasonable. So if the min/max plugin is active we always show the min/max admin inputs and require both be filled in order to have a fixed size.

What about products that were created prior to min/max plugin activation? Those won't have a max meta? I guess we can differentiate between null meta and a non-existent meta key. 

Should I leave [these filters](https://github.com/woothemes/woocommerce-mix-and-match-products/commit/b15af2cab6b2bb6b7e6ecbf89d779a1e5cd7c74a) in? We'll still need them right? Or only the max?

**Comment by manospsyx** [comment]
I'm starting to follow now :)

Wouldn't it be much simpler if we just put this in plugin core? It seems like it belongs there.

In this case:

> I guess we can differentiate between null meta and a non-existent meta key.

**Comment by manospsyx** [comment]
So if a Max meta doesn't exist, use the old/standard/existing meta as Max, otherwise use the Max :)
(edited)

**Comment by helgatheviking** [comment]
> I'm starting to follow now :)

me too!

I'm hesitant to put it in core right away. As you've said, you can't ever take it out again. :+1: 

Another thing that goes a little wonky if we replace the container size with a min container size... the unlimited "0" containers. Right now we're using 0 as a placemarker for infinity. A actual minimum can never be 0 (unless we want to delve into empty containers) and would always be 1.

**Comment by helgatheviking** [comment]
Thoughts on those filters though? I put a hold on the 1.0.6 release to maybe add them. I'm headed to the beach in an hour, but could retag the release before i go.

**Comment by manospsyx** [comment]
> I'm hesitant to put it in core right away. As you've said, you can't ever take it out again.

You just convinced me :)

> Another thing that goes a little wonky if we replace the container size with a min container size... the unlimited "0" containers.

This is all sorted by looking at whether the max meta exists...

I'd say we make this work before we release 1.0.6, just in case we need to change more things there. Can you keep looking into it? It shouldn't take more than a couple hours -- but I'd be happy to help if you get stuck.

**Comment by manospsyx** [comment]
> Thoughts on those filters though?

Same - let's finish the mini-extension first, then see if we'll need them or not. I think we will.

Mini-extension work always exposes small issues and helps perfect the underlying infrastructure, so it's probably a good idea to postpone 1.0.6 for a day or two, we won't need more.

**Comment by helgatheviking** [comment]
> So if a Max meta doesn't exist, use the old/standard/existing meta as Max, otherwise use the Max :)

that could work. and similarly, should handle any existing 0 sizes. (though the label saying minimum and the value being 0 is a little odd, but not major)

> You just convinced me :)

glad i could help!

1.0.6 also had some bug fixes though: price strings and and quantity inputs for unlimited containers. I'd kind of like to push them out. We could always push out 1.0.7 with whatever fixes are required to play nice with the mini extension.

I won't be able to work on this until tomorrow. Hey, I'm in hawaii and have to go the beach. :palm_tree: :ocean: :sunglasses:  It's important.

**Comment by manospsyx** [comment]
:+1: for 1.0.6 then + let's leave the hooks in.

> Hey, I'm in hawaii and have to go the beach.

xD What? You still here? Go!

**Comment by helgatheviking** [comment]
1.0.6 tagged and card moved. And i'm out!

**Comment by helgatheviking** [comment]
I'm 97% sure this is resolved, so i am closing it.
